add_requires("benchmark")
add_requires("gtest", {configs = {main = true}})
add_includedirs(".")
add_deps("absl")

-- target("test_all")
--     set_kind("binary")
--     add_files("absl/**/**.cc")
--     add_packages("gtest","benchmark")
--     if is_plat("windows") then
--         -- fixes "LINK : fatal error LNK1561: entry point must be defined"
--         add_ldflags("/subsystem:console")
--     end
--     add_defines("_DISABLE_EXTENDED_ALIGNED_STORAGE","NOMINMAX")

includes("absl/algorithm")
includes("absl/base")
includes("absl/cleanup")
includes("absl/container")
includes("absl/copts")
includes("absl/crc")
includes("absl/debugging")
includes("absl/flags")
includes("absl/functional")
includes("absl/hash")
includes("absl/log")
includes("absl/memory")
includes("absl/meta")
includes("absl/numeric")
includes("absl/profiling")
includes("absl/random")
includes("absl/status")
includes("absl/strings")
includes("absl/synchronization")
includes("absl/time")
includes("absl/types")
includes("absl/utility")